### ISSUE TITLE
Merge into core Plone

### ISSUE THREAD

**Issue by mauritsvanrees** [RedTurtle/experimental.ulocalized_time#1]
I would like to merge this package into Plone core.
See https://github.com/plone/Products.CMFPlone/issues/3549

**Comment by cekk** [comment]
cool! is there something that i need to do?

**Comment by mauritsvanrees** [comment]
You could review the PR: https://github.com/plone/plone.base/pull/11

**Comment by mauritsvanrees** [comment]
Done.
